export const vaccines = [
  {
    id: 0,
    name: 'BBIBP-CorV',
    inventor: 'Sinopharm',
    place: 'Chine',
    technology: 'virus inactivé',
    quantity: 420,
    price: 17,
    approved: true,
  },
  {
    id: 1,
    name: 'Sputnik V',
    inventor: 'Gamaleya',
    place: ['Russie', ' Inde'],
    technology: 'adenovirus',
    quantity: 130,
    price: 12,
    approved: false,
  },
  {
    id: 2,
    name: 'AZD1222',
    inventor: ['AstraZeneca', ' University of Oxford'],
    place: ['Royaume Uni', ' Brésil', ' Inde'],
    technology: 'adenovirus',
    quantity: 5028,
    price: 1.78,
    approved: false,
  },
  {
    id: 3,
    name: 'Tozinameran',
    inventor: ['BioNTech', ' Pfizer', ' Fosun Pharma'],
    place: ['Allemagne', ' USA'],
    technology: 'ARN messager',
    quantity: 980,
    price: 14,
    approved: true,
  },
  {
    id: 4,
    name: 'mRNA-1273',
    inventor: ['Moderna', ' NIAID', ' BARDA'],
    place: 'USA',
    technology: 'ARN messager',
    quantity: 240,
    price: 28,
    approved: false,
  },
  {
    id: 5,
    name: 'Ad26.COV2.S',
    inventor: ['Johnson & Johnson', ' BIDMC'],
    place: ['USA', ' Amérique du Sud', ' Ukraine', ' Afrique du Sud'],
    technology: 'adenovirus',
    quantity: 110,
    price: 31,
    approved: false,
  },
];
